name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:

    - uses: actions/setup-go@v1
      with:
        go-version: 1.14
      id: go
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.102'

    - name: Test stdlib
      working-directory: test/stdlib
      run: |
        ./run.sh fmt -test.v -test.run=^Test
        ./run.sh math -test.v -test.run=^Test
        ./run.sh math/bits -test.v -test.run=^Test
        ./run.sh sort -test.v -test.run=^Test

    - name: Test binding
      working-directory: test/binding
      run: ./run.sh
